### ISSUE TITLE
Support for import with variables

### ISSUE THREAD

**Issue by matejsp** [gabrysbiz/lesscss-extended-compiler#5]
I would like to use: http://lesscss.org/features/#variables-feature-import-statements

// Variables
@themes: "../../src/themes";

// Usage
@import "@{themes}/tidal-wave.less";

But it is not working.

**Comment by agabrys** [comment]
The library manages imports on their own (hack "how to solve problems with fetching files from Internet"). I want to rewrite it, that it will support source maps. I hope that during the refactoring I will also fix this bug (but I'm not sure - it will be really hard to determine variable value).

Unfortunately the rewritten version will be not available in this year (I'm sure at 90%).

**Comment by agabrys** [comment]
Today I started working on Less Compiler 2.0.0. It will handle imports with variables. This library will be deprecated after release of Less Compiler 2.0.0, so I marked this bug as "Won't fix".

See [gabrysbiz/lesscss-compiler#milestone 2.0.0](/gabrysbiz/lesscss-compiler/milestone/2)
